### ISSUE TITLE
Implement new UI

### ISSUE THREAD

**Issue by joostdevries** [alexspeller/ember-twiddle#5]
The lovely mr @kevinrudyanderson has done some work on a UI for this. Tracking work on that here..

## First version

![image](https://cloud.githubusercontent.com/assets/3824616/7666998/a88adb14-fbfa-11e4-9ac9-34eb8082a04c.png)

## Todo
- [x] Main layout
  - [x] Menubar
    - [x] Twiddle name + version (eg. "My twiddle @ abf34c2")
  - [x] Fonts
  - [x] Colors
- [ ] File menu
  - [x] Add resource
    - [x] Add component
    - [x] Add controller
    - [ ] Add resource (pod)
    - [x] Add template
  - [x] Delete file (in active column)
  - [x] Rename file / move filefile (in active column)
  - [x] Fork Twiddle
  - [x] Share Twiddle
    - [ ] Embed
    - [x] URL
  - [x] Delete Twiddle?
- [x] User menu
  - [x] Sign in
  - [x] Sign out
- [x] Editor column
  - [x] File picker dropdown (make it clear it's a dropdown)
  - [x] Focus active column
  - [ ] Type label
  - [ ] Resizable
- [x] Informational
  - [x] Build errors
  - [x] Succesful builds - Output updated
  - [x] Twiddle saved/committed

**Comment by joostdevries** [comment]
@tomdale suggested that in addition to "Add file" we could use generators to provide generated files:
- Add adapter
- Add component
- Add controller
- Add model
- Add resource (as pod)
- Add route
- Add serializer
- Add template

**Comment by joostdevries** [comment]
Feedback from @mixonic "looks like great progress. At first glance I feel it could use a splash of color."

**Comment by kevinrudyanderson** [comment]
Updated the dropdown menu
Changed the title
Added last saved state
Added a dropdown to the file picker

http://cl.ly/azWo

**Comment by joostdevries** [comment]
Pretty much got everything in there.. http://twiddle.joostdvrs.com/

**Comment by joostdevries** [comment]
@kevinrudyanderson instead of the big label, could you use something like this (in the editor?)

![image](https://cloud.githubusercontent.com/assets/3824616/7675665/6d8d9118-fd3b-11e4-8f21-df8fc1b4aef9.png)

taken from http://guides.emberjs.com/v1.10.0/controllers/representing-a-single-model-with-objectcontroller/
